### ISSUE TITLE
does not seem to work with dist specified in targets

### ISSUE THREAD

**Issue by mikois** [dev5c32373043/parcel-reporter-clean-dist#9]
Hi,

I've a parcel 2.8.3 and parcel-reporter-clean-dist 1.0.4 - its a fresh experimental install with no clutter.

.parcelrc
{
  "extends": ["@parcel/config-default"],
(...)
  "reporters":  ["...", "parcel-reporter-clean-dist"]

package.json
{
(...)
"targets":{
default:{
distDir:"C:\\Users\\someuser\\OneDrive - Company\\Site Assets\\dist"

works fine for parcel build  and parcel watch, but does not seem to clear the target distDir. Builds without errors or messages.

Cheers,
M

**Comment by dev5c32373043** [comment]
Hi, sorry for such an instant response⚡😅 
I've checked your issue on windows and found no problems on the library side.
Btw. I couldn't test path with backslashes because it causes `Invalid escape character in string` error (backslashes are escape characters in JSON).
I suggest you to use forward slashes instead. They work fine on both windows and unix-based systems.
